version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
    - ./nginx/conf/default.conf/:/etc/nginx/conf.d/default.conf
    - ./../../../public/:/var/www/project/public/
    ports:
    - "80:80"
    restart: always
    extra_hosts:
    - "web.localhost:127.0.0.1"
    - "student.localhost:127.0.0.1"
    depends_on:
    - fpm
    links:
    - fpm

  fpm:
    build:
      context: ./
      dockerfile: ./fpm/Dockerfile
    volumes:
    - ./../../../:/var/www/project/
    environment:
      DB_HOST: "postgres"
      REDIS_HOST: "redis"
    restart: always
    extra_hosts:
    - "fpm.localhost:127.0.0.1"
    depends_on:
    - postgres
    - redis
    links:
    - postgres
    - redis

#  cli:
#    container_name: "cli"
#    build:
#      context: ./
#      dockerfile: ./cli/Dockerfile
#    volumes:
#    - ./../../../:/var/www/project/
#    environment:
#      SKIP_SUPERVISOR_CRON: "true"
##      SKIP_SUPERVISOR_CRON: "false"
#      DB_HOST: "postgres"
#      REDIS_HOST: "redis"
#    restart: always
#    extra_hosts:
#    - "cli.localhost:127.0.0.1"
#    labels:
#    - type=cli-php
#    - project=${APP_NAME}
#    depends_on:
#    - postgres
#    - redis
#    links:
#    - postgres
#    - redis

  postgres:
    container_name: "postgres"
    build:
      context: ./
      dockerfile: ./postgres/Dockerfile
    #expose this in order to use in your IDE
    ports:
    - "5432:5432"
    volumes:
    - ~/dockerData/${APP_NAME}-${APP_DATABASE}/postgresData:/var/lib/postgresql/data/
    env_file:
    - ./../../../.env
    environment:
    - "POSTGRES_DB=${DB_DATABASE}"
    - "POSTGRES_USER=${DB_USERNAME}"
    - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    extra_hosts:
    - "postgres.localhost:127.0.0.1"

  redis:
    container_name: "redis"
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    extra_hosts:
    - "redis.localhost:127.0.0.1"
    sysctls:
      net.core.somaxconn: '511'